Repository 2024Capstone-6/project_react-deployment-repo, pull requests merged in 2024-12, with the labels that each got.

#12 Feat/reactdg
  src/App.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: :art: Html & Css, :star2: Feature

#13 Feat/special
  package-lock.json
  package.json
  src/components/Add_Modal.tsx
  src/components/Delete_Modal.tsx
  src/components/Fail_Modal.tsx
  src/components/Ok_Modal.tsx
  src/components/Update_Modal.tsx
  src/pages/Board.tsx
  src/pages/Japan.tsx
  src/pages/Login.tsx
  src/pages/Member.tsx
  src/pages/Special.tsx
  tailwind.config.js
Labels: :star2: Feature

#18 Feat/japan
  src/components/JapaneseModal.tsx
  src/pages/Japan.tsx
Labels: :lady_beetle: Bug, :+1: Enhancement, :art: Html & Css, :star2: Feature

#17 Feat/board 🎨 Html & Css 🌟 Feature
  .gitignore
  package-lock.json
  src/App.tsx
  src/pages/Board.tsx
  src/pages/Board/Board.tsx
  src/pages/Board/BoardIN.tsx
  src/pages/Board/CrateBoard.tsx
  src/pages/Board/UpdateBoard.tsx
  src/style/board.css
Labels: :art: Html & Css, :star2: Feature
