Repository 2024Capstone-6/project_react-deployment-repo, pull requests merged in 2024-11, with the labels that each got.

#2 [FEAT] 사이드 네비게이션 바 생성 및 콘텐츠 기본 위치 설정
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/Navbar.tsx
  src/index.tsx
  src/styles/navbar.css
  tailwind.config.js
Labels: :art: Html & Css, :star2: Feature

#4 [BUG] index.html 및 index.tsx 파일 수정
  public/index.html
  src/index.tsx
Labels: :lady_beetle: Bug, :+1: Enhancement

#10 ✨ feat: 페이지 및 경로 추가
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/Special.tsx
Labels: :star2: Feature
